name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:[![Docker Image CI](https://github.com/Tofigh11/atom/actions/workflows/docker-image.yml/badge.svg?branch=master&event=create)](https://github.com/Tofigh11/atom/actions/workflows/docker-image.yml)

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
